name = "restaurant-dashboard-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "development"

# Staging environment
[env.staging]
name = "restaurant-dashboard-api-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

# Production environment  
[env.production]
name = "restaurant-dashboard-api-prod"
[env.production.vars]
ENVIRONMENT = "production"